### ISSUE TITLE
L'application ne lit aucune histoire

### ISSUE THREAD

**Issue by gdumanoir** [Cyri1/bah#3]
Bonjour 

J'ai suivi le mode d'emploi, j'ai mis les droits pour tous les fichiers pour l'application.
J'ai installé un pack d'histoire, et quand je vais sur l'écran principal, je n'ai rien à part les deux boutons jaunes.
Qu'aurais je manqué ?

Merci bien

**Comment by Cyri129** [comment]
Salut,
Quel est ton modèle de tél ?
Est ce que tu as bien un dossier packs/dossier_avec_le_nom_de_lhistoire/ contenant un dossier assets et un fichier story.json?

Je te suggère d'aller dans la section appropriée du discord que tu trouveras dans le readme de ce dépôt github pour obtenir du support.

**Comment by gdumanoir** [comment]
J'ai un Galaxy A32 
L'arborescence me semble OK 
![Screenshot_20230210-141307_My Files](https://user-images.githubusercontent.com/10836635/218101019-62385970-5817-4b0c-8745-a7f9ff214ed6.jpg)
![Screenshot_20230210-141327_My Files](https://user-images.githubusercontent.com/10836635/218101027-695ade3f-b9fa-4d8d-b85f-bef3247dcadc.jpg)

**Comment by Cyri129** [comment]
Ben non du coup, vu que tu as mis un zip ^^

**Comment by gdumanoir** [comment]
> Ben non du coup, vu que tu as mis un zip ^^

J'ai eu un doute, mais c'est bien un répertoire dont le nom se finit par .zip.
J'ai compressé le répertoire, pour en faire un fichier zip, l'icône est différente 

![Screenshot_20230211-174129_My Files](https://user-images.githubusercontent.com/10836635/218270074-d53e20ca-b9fa-4b33-a7e3-04ee270e49fb.jpg)

Le répertoire à été installé par l'application depuis le store externe...

**Comment by Cyri129** [comment]
problème de droits alors, tu as android 13 ?
je crois que la gestion des droits est un peu différente sur cette version d'android
voici un tuto fait par un utilisateur android 13 si c'est le cas :
[Tuto_boite_a_Histoire_autorisation_Android_13_by_tiiiit-74.pdf](https://github.com/Cyri1/bah/files/10720954/Tuto_boite_a_Histoire_autorisation_Android_13_by_tiiiit-74.pdf)

**Comment by gdumanoir** [comment]
Je suis en Android 11.
J'ai redémarré le tel, supprimé le cache et les données : idem
Est ce que j'ai un moyen de voir les logs de l'application ? Est ce que je peux activer une option de début ?

**Comment by Cyri129** [comment]
Tu utilises quelle version de l'app ? 
Pour voir des logs il faut : 
- activer le débogage usb
- brancher le tel à un PC
- ouvrir Chrome et entrer dans l'url : chrome://inspect/#devices
- ensuite tu auras un bouton inspect sur la page de Chrome

Si tu veux des réponses rapide va sur le discord https://monurl.ca/lunii.creations car ici j'ai pas de notif quand tu réponds
