### ISSUE TITLE
Écran blanc

### ISSUE THREAD

**Issue by vpoulailleau** [Cyri1/bah#6]
Bonjour,

Je viens d'essayer l'application sur Android 6 et 7, et j'ai le même résultat : je vois le logo de l'application au démarrage de l'application (et sous Android 7 j'ai aussi les 3 boutons carré triangle rond). Puis 2-3 secondes plus tard, l'écran devient tout blanc et il ne se passe plus rien.

Avez-vous une piste ? Puis-je fournir des infos pour aider ?

PS : merci pour l'initiative d'avoir fait une fabrique à histoire pour Android

**Comment by Cyri129** [comment]
Bonjour, essayez de mettre a jour Android WebView et vérifiez dans les options pour les développeurs que vous avez bien Android WebView de sélectionné.

**Comment by vpoulailleau** [comment]
Ça a marché ! Merci beaucoup ! Ça va faire deux heureuses, les fabriques à histoires d'origine ont été abîmées.

**Comment by vpoulailleau** [comment]
Et pour ceux qui tombent sur cette issue, la mise à jour se passe ici : https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en&gl=US&pli=1
