### ISSUE TITLE
[Feature Request] Stockage des histoires sur la MicroSD

### ISSUE THREAD

**Issue by gab12** [Cyri1/bah#7]
Bonjour Cyril,
Bravo pour ton incroyable travail, qui aide énormément mon fils à s'endormir.
BAH est installé sur sa tablette. Alors qu'il n'a que quelques histoires  (10), elles saturent sa tablette car ca prend énormément de place.
Il serait super, si les histoires pouvaient etre installées ailleurs quand dans /Documents notamment si on pouvait les positionner sur la MicroSD. Ainsi on pourrait en mettre beaucoup plus sans saturer l'appareil.

Voilà c'est une suggestion Merci d'avance

**Comment by Cyri129** [comment]
Salut, tu es pas la première personne à me demander ça et c'est sur ça que je travaille actuellement mais pour l'instant ça fonctionne pas comme je voudrais

**Comment by gab12** [comment]
Ok merci pour ton retour. Je clos la demande si elle est déjà dans les tuyaux. On croise tous les doigts pour que tu trouves la solution en attendant alors :

**Comment by Cyri129** [comment]
Fonctionnalité ajouté dans la version 1.1.0
