### ISSUE TITLE
les histoires n'apparaissent pas

### ISSUE THREAD

**Issue by sdk69** [Cyri1/bah#8]
Bonjour,

J'ai bien donné la permission pour l'accès à tous les fichiers
Mon répertoire "packs" existe bien dans Documents et j'y ai mis les histoires que j'avais au format dossier nommé avec le nom de l'histoire, qui contient les assets et le story.json
Hélas les histoires n'apparaissent pas dans l'écran principal, elles sont en revanche toutes visibles dans les paramètres onglet "mes histoires" ou elles ont bien l'icone pour qu'elles apparaissent et ou je peux aussi les supprimer.

Avez vous une idée ? je n'arrive pas à accéder au Discord, merci !

**Comment by Dark-Stories** [comment]
Bonjour, il faut qu'il y ait QUE des dossiers contenant des histoires dans le dossier Documents/packs/.
Pas de zip qui traine ou autre fichier.
Le Discord : https://monurl.ca/lunii.creations

**Comment by sdk69** [comment]
Parfait c'était bien ça il y avait un dossier dont le contenu était au format converti au milieu ! Merci beaucoup !!

**Comment by gab12** [comment]
Bonjour,
Comment vous avez résolu le problème ?
J'ai exactement le même, bien que présent dans le répertoire et visible dans le menu paramètre/mes histoires, elles n'apparaissent pas dans l'écran principale. On ne peut donc les écouter. Sur les 2 téléphones que j'ai : Android 13 et 14.
C'est très frustrant :'(

**Comment by sdk69** [comment]
Bonjour, il faut qu'il y ait QUE des dossiers contenant des histoires dans le dossier Documents/packs/.
Pas de zip qui traine ou autre fichier.

**Comment by gab12** [comment]
Merci beaucoup.
A priori ce nest pas le meme probleme car tout semble conforme chez moi bien que je t avourais que je ne connaissais pas cette subtilité assez piegieuse. Merci en tout cas. Du tout je vais ouvrir un ticket dédié. Merci encore

**Comment by gab12** [comment]
Ok Super. Je ne connaissais pas cette subtilité. Ca a aidé car j'avais effectivement les zip dedans.
Mais ca n'avait pas suffit. Il faut également forcer l'autorisation d'accéder au dossier.
D'habitude l'appli le signale et ouvre la page de paramètre, ici je pense que cyril ne l'a pas implémenté. Il faut donc le faire manuellement et le parcours n'est pas simple car il n'est pas dans les autorisations basique de l'appli.
C'est dans paramètre de Android / Applications /  menu ... en haut à droite / Gestionnaire d'autorisations / Fichiers et contenus multimédias / Voir plus d'applis pouvant accéder à tous les fichiers / Boite à Histoires et activer l'option.

Voilà si ca peut aider. En tout cas merci sdk69 pour ton aide 🙏🏻
Mon fils est du coup très content :)
